Slam 60
UTRA-ART/SLAM pull request #77
Opened 2020-02-20 18:53 UTC by 1999michael

You must type in the terminal you used to launch move_base.launch for keyboard teleop
----------------------------------------
to move around the robot, use the following (in lower case, no shift, 8 cardinal directions):
u  i  o
j  k  l
m ,  .

'space' indicates that you will return from manual control to move_base automatic control

2020-02-21 01:07 UTC, erickmu1 requested changes
Do we need the `test/` folder for the `twist_mux` package?

2020-02-21 01:07 UTC, erickmu1 commented on slam-ws/src/nav_stack/launch/move_base.launch
> +  <arg name="config_topics" default="$(find twist_mux)/config/twist_mux_topics.yaml"/>
arguments should be placed at the top of `launch` files (see how other `launch` file define arguments)

2020-02-21 01:07 UTC, erickmu1 commented on slam-ws/src/nav_stack/launch/move_base.launch
> +  </node>
Can we make a separate `launch` file for teleop keyboard? I don't think we need teleop to run every time we run `move_base` but rather we should call it if we need it

2020-02-21 01:07 UTC, erickmu1 commented on slam-ws/src/nav_stack/launch/move_base.launch
> +  </node>
Can you add comments to what these do? I understand they launch the `twist_mux` but why do we need to launch two nodes?

2020-02-21 01:07 UTC, erickmu1 commented on slam-ws/src/nav_stack/launch/move_base.launch
> +  </node>
Also, keep `twist_mux` with `move_base` since we always want this mux to exist when issuing `cmd_vel`s

2020-02-23 02:26 UTC, erickmu1 requested changes
`rostest` error when I attempted to `catkin_make` locally, I believe we want to remove this dependency given that we are not using it atm

2020-02-26 06:15 UTC, 1999michael commented
> `rostest` error when I attempted to `catkin_make` locally, I believe we want to remove this dependency given that we are not using it atm

fixed

2020-02-26 13:51 UTC, erickmu1 commented on slam-ws/src/twist_mux/CMakeLists.txt
> -endif()
I believe this is a valid fix, but is it potentially possible to set the `CATKIN_ENABLE_TESTING` flag to `false`?

2020-02-26 13:51 UTC, erickmu1 commented on slam-ws/src/transform/launch/setup_tf.launch
> -    <arg name="robot_model" defaul="husky_gazebo"/>
Merge the current `dev` onto your branch and this fix will already be implemented

2020-02-26 13:54 UTC, erickmu1 commented on slam-ws/src/motor_control/config/twist_mux_topics.yaml
> +  priority: 30
missing new line

2020-02-26 22:39 UTC, 1999michael commented on slam-ws/src/motor_control/config/twist_mux_topics.yaml
> +  priority: 30
removed file (redundant with original file)

2020-02-27 02:42 UTC, erickmu1 approved these changes
I tested it and it works!

2020-02-27 02:43 UTC, merged